# Generated by Django 6.1 on 2026-08-14 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_score', models.PositiveSmallIntegerField(help_text='Achievement and outcome (out of 35)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('methodology_score', models.PositiveSmallIntegerField(help_text='Methodology of the service / project (out of 20)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('creativity_score', models.PositiveSmallIntegerField(help_text='Creativity and innovation (out of 10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('execution_score', models.PositiveSmallIntegerField(help_text='Execution of the service / project (out of 35)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('comments', models.TextField(blank=True, help_text="Juror's overall experience / remarks on this entry")),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.juror')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_reviews', to='awards.nomination')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('juror', 'nomination')},
            },
        ),
    ]
