# Generated by Django 6.1 on 2026-08-18 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('awards', '0006_category_judging_deadline'),
        ('jury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to='accounts.juror')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='awards.nomination')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('juror', 'nomination')},
            },
        ),
    ]
