# Generated by Django 6.1 on 2026-08-19 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0002_recentlyviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juryreview',
            name='achievement_score',
            field=models.PositiveSmallIntegerField(help_text='Achievement and outcome (6–10, minimum 6 mandatory)', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='juryreview',
            name='creativity_score',
            field=models.PositiveSmallIntegerField(help_text='Creativity and innovation (6–10, minimum 6 mandatory)', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='juryreview',
            name='execution_score',
            field=models.PositiveSmallIntegerField(help_text='Execution of the service / project (6–10, minimum 6 mandatory)', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='juryreview',
            name='methodology_score',
            field=models.PositiveSmallIntegerField(help_text='Methodology of the service / project (6–10, minimum 6 mandatory)', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
