# Generated by Django 6.1 on 2026-08-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='jurors/')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive jurors cannot log in even with a valid code.')),
                ('nda_accepted', models.BooleanField(default=False)),
                ('nda_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_categories', models.ManyToManyField(blank=True, related_name='assigned_jurors', to='awards.category')),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='accounts.juror')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
