# Generated by Django 6.1 on 2026-08-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('level', models.CharField(choices=[('individual', 'Individual Category'), ('organizational', 'Organizational Level Category')], default='individual', max_length=20)),
                ('sector', models.CharField(choices=[('public', 'Public & Government Sector'), ('private', 'Private Sector'), ('na', 'Not sector-specific')], default='na', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_open_for_judging', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, help_text="e.g. 'Government Sector'", max_length=255)),
                ('city_country', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('nominee_full_name', models.CharField(blank=True, max_length=255)),
                ('nominee_job_title', models.CharField(blank=True, max_length=255)),
                ('nominee_address', models.CharField(blank=True, max_length=255)),
                ('employee_headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('project_title', models.CharField(blank=True, max_length=255)),
                ('project_highlights', models.TextField(blank=True)),
                ('key_achievements', models.TextField(blank=True)),
                ('reason_for_nomination', models.TextField(blank=True)),
                ('business_impact', models.TextField(blank=True)),
                ('reference_code', models.CharField(blank=True, help_text='Internal tracking code, optional', max_length=50)),
                ('is_visible_to_jury', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='awards.category')),
            ],
            options={
                'ordering': ['organization_name'],
            },
        ),
        migrations.CreateModel(
            name='NominationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Supporting Document (PDF)', max_length=255)),
                ('file', models.FileField(upload_to='nominations/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='awards.nomination')),
            ],
        ),
        migrations.CreateModel(
            name='NominationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='awards.nomination')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
