# Generated by Django 6.1 on 2026-08-17 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationdocument',
            name='file',
            field=models.FileField(help_text='Accepted formats: PDF, GIF, JPEG, PNG, MOV, MP4.', upload_to='nominations/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'gif', 'jpg', 'jpeg', 'png', 'mov', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='nominationdocument',
            name='label',
            field=models.CharField(default='Supporting Document', max_length=255),
        ),
    ]
