# Generated by Django 6.1 on 2026-08-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_nominationdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='award_notes',
            field=models.TextField(blank=True, help_text='Optional internal notes about the final decision (not shown to jurors).'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='award_tier',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('winner', 'Winner'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('finalist', 'Finalist'), ('shortlisted', 'Shortlisted')], default='', help_text='Set once the secretariat has decided the result for this nomination.', max_length=20),
        ),
    ]
