# Generated by Django 6.1 on 2026-08-17 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_nomination_award_notes_nomination_award_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationdocument',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube (or Vimeo) link, if not uploading a video file directly. Leave blank if using File instead.'),
        ),
        migrations.AlterField(
            model_name='nominationdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Accepted formats: PDF, GIF, JPEG, PNG, MOV, MP4. Leave blank if using a Video URL instead.', upload_to='nominations/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'gif', 'jpg', 'jpeg', 'png', 'mov', 'mp4'])]),
        ),
    ]
