# Generated by Django 6.1 on 2026-08-17 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_nominationdocument_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Accepted formats: PDF, GIF, JPEG, PNG, MOV, MP4, DOCX, PPTX. Leave blank if using a Video URL instead.', upload_to='nominations/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'gif', 'jpg', 'jpeg', 'png', 'mov', 'mp4', 'docx', 'pptx'])]),
        ),
    ]
