# Generated by Django 6.1 on 2026-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_alter_nominationdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='judging_deadline',
            field=models.DateTimeField(blank=True, help_text='Optional. After this date/time, jurors can no longer submit or update scores for this category — enforced automatically, not just advisory.', null=True),
        ),
    ]
